
package com.apex.livebos.ws;

import oracle.net.ano.Service;

import org.apache.tomcat.util.net.URL;
import org.dom4j.QName;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LBEBusinessWebService", targetNamespace = "http://ws.livebos.apex.com/", wsdlLocation = "http://192.168.100.12:8080/service/LBEBusiness?wsdl")
public class LBEBusinessWebService
    extends Service
{

    private final static URL LBEBUSINESSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LBEBUSINESSWEBSERVICE_EXCEPTION;
    private final static QName LBEBUSINESSWEBSERVICE_QNAME = new QName("http://ws.livebos.apex.com/", "LBEBusinessWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.100.12:8080/service/LBEBusiness?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LBEBUSINESSWEBSERVICE_WSDL_LOCATION = url;
        LBEBUSINESSWEBSERVICE_EXCEPTION = e;
    }

    public LBEBusinessWebService() {
        super(__getWsdlLocation(), LBEBUSINESSWEBSERVICE_QNAME);
    }

    public LBEBusinessWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LBEBUSINESSWEBSERVICE_QNAME, features);
    }

    public LBEBusinessWebService(URL wsdlLocation) {
        super(wsdlLocation, LBEBUSINESSWEBSERVICE_QNAME);
    }

    public LBEBusinessWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LBEBUSINESSWEBSERVICE_QNAME, features);
    }

    public LBEBusinessWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBEBusinessWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LBEBusinessService
     */
    @WebEndpoint(name = "LBEBusinessServiceImplPort")
    public LBEBusinessService getLBEBusinessServiceImplPort() {
        return super.getPort(new QName("http://ws.livebos.apex.com/", "LBEBusinessServiceImplPort"), LBEBusinessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LBEBusinessService
     */
    @WebEndpoint(name = "LBEBusinessServiceImplPort")
    public LBEBusinessService getLBEBusinessServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.livebos.apex.com/", "LBEBusinessServiceImplPort"), LBEBusinessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LBEBUSINESSWEBSERVICE_EXCEPTION!= null) {
            throw LBEBUSINESSWEBSERVICE_EXCEPTION;
        }
        return LBEBUSINESSWEBSERVICE_WSDL_LOCATION;
    }

}
