package com.tbea.ic.operation.service.wgcpqk.wgcpylnlspcs;

public enum WGCPYLNL_BYQ_MLL_Type{

	MLSPCS_BYQ_DYDJ_JLBYQ(23),
	MLSPCS_BYQ_DYDJ_JLBYQ_35KV_YX(24),
	MLSPCS_BYQ_DYDJ_JLBYQ_66_110KV(25),
	MLSPCS_BYQ_DYDJ_JLBYQ_220KV(26),
	MLSPCS_BYQ_DYDJ_JLBYQ_330KV(27),
	MLSPCS_BYQ_DYDJ_JLBYQ_500KV(28),
	MLSPCS_BYQ_DYDJ_JLBYQ_750KV(29),
	MLSPCS_BYQ_DYDJ_JLBYQ_1000KV(30),
	MLSPCS_BYQ_DYDJ_ZLBYQ(31),
	MLSPCS_BYQ_DYDJ_ZLBYQ_400KV_YX(32),
	MLSPCS_BYQ_DYDJ_ZLBYQ_500KV(33),
	MLSPCS_BYQ_DYDJ_ZLBYQ_600KV(34),
	MLSPCS_BYQ_DYDJ_ZLBYQ_800KV(35),
	MLSPCS_BYQ_DYDJ_ZLBYQ_PBDKQ(36),
	MLSPCS_BYQ_DYDJ_DKQ(37),
	MLSPCS_BYQ_DYDJ_DKQ_330KV_YX(38),
	MLSPCS_BYQ_DYDJ_DKQ_500KV(39),
	MLSPCS_BYQ_DYDJ_DKQ_750KV(40),
	MLSPCS_BYQ_DYDJ_DKQ_1000KV(41),
	
	SBDCZCLWCQK_CZ_BYQ_DYDJ_GSBYQ(42),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_GSBYQ_F(43),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_GSBYQ_H(44),
	//SBDCZCLWCQK_CZ_BYQ_DYDJ_GSBYQ_XSBDZ(45),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_GSBYQ_GSDKQ(46),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_77(77),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_78(78),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_79(79),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_80(80),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_QT_86(86),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_81(81),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_82(82),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_83(83),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_84(84),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_QT_87(87),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ(47),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ_ZLB(49),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ_QYB(50),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ_GBB(48),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ_YTB(51),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_TZBYQ_QT(52),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSL(53),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSL_PDZDH(54),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSL_KG(55),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSL_TG(56),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSL_HGQ(57),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSLWXPJ(58),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_YSLWXPJ_QT(85);
	
	
    private int _value;

    private WGCPYLNL_BYQ_MLL_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}