CREATE TABLE [dbo].[CUX_QUALITY_ISSUE_IN_CTRL_T](
	[ID] [numeric](18, 0) NOT NULL,
	[BATCH_NO] [nvarchar](30) NOT NULL,
	[CTRL_FLAG] [nvarchar](50) NOT NULL,
	[TASK_OWNER] [nvarchar](50) NOT NULL,
	[START_DATE] [datetime] NOT NULL,
	[END_DATE] [datetime] NULL,
	[ATTRIBUTE1] [nvarchar](240) NULL,
	[ATTRIBUTE2] [nvarchar](240) NULL,
	[ATTRIBUTE3] [nvarchar](240) NULL,
	[ATTRIBUTE4] [nvarchar](240) NULL,
	[ATTRIBUTE5] [nvarchar](240) NULL
) ON [PRIMARY]


CREATE TABLE [dbo].[CUX_QUALITY_ISSUE_IN_T](
	[BATCH_NO] [nvarchar](240) NOT NULL,
	[D_CODE] [nvarchar](10) NOT NULL,
	[STATUS] [nvarchar](10) NULL,
	[STATUS_DESC] [nvarchar](1000) NULL,
	[ISSUE_NO] [nvarchar](50) NOT NULL,
	[D_NAME] [nvarchar](240) NOT NULL,
	[ISSUE_HAPPEN_DATE] [datetime] NOT NULL,
	[PRODUCT_TYPE] [nvarchar](240) NOT NULL,
	[PRODUCTION_NUM] [nvarchar](240) NOT NULL,
	[PRODUCTION_MODEL] [nvarchar](240) NOT NULL,
	[ISSUE_TYPE] [nvarchar](240) NOT NULL,
	[SUB_ISSUE_TYPE] [nvarchar](240) NOT NULL,
	[CATEGORY_CODE] [nvarchar](50) NOT NULL,
	[QUALITY_PHENOMENON] [nvarchar](240) NOT NULL,
	[DETAIL] [nvarchar](1000) NOT NULL,
	[MATERIAL_COUNT] [numeric](18, 0) NOT NULL,
	[MEASUREMENT_UNITS] [nvarchar](50) NOT NULL,
	[SCM_V_ID] [numeric](18, 0) NOT NULL,
	[VENDOR_NAME] [nvarchar](240) NOT NULL,
	[RESPONSIBILITY_DEPT] [nvarchar](240) NOT NULL,
	[FILLING_PERSONNEL] [nvarchar](240) NOT NULL,
	[PRODUCT_DELIVERY_DATE] [datetime] NOT NULL,
	[FAILURE_SUBJECT] [nvarchar](240) NOT NULL,
	[MATERIAL_TREATMENT_MEASURE] [nvarchar](240) NOT NULL,
	[ONSITE_TREATMENT_MEASURE] [nvarchar](240) NOT NULL,
	[ONSITE_TREATMENT_RESULT] [nvarchar](240) NOT NULL,
	[USER_UNIT] [nvarchar](240) NOT NULL,
	[ONSITE_AFTER_SALES] [nvarchar](50) NOT NULL,
	[AFTER_SALES_TEL] [nvarchar](50) NOT NULL,
	[MATERIAL_HAPPEN_PHASE] [nvarchar](240) NOT NULL,
	[ISSUE_PROCESS] [nvarchar](240) NOT NULL,
	[CAUSA_ANALYSIS] [nvarchar](240) NOT NULL,
	[ASSESSMENT] [nvarchar](240) NOT NULL,
	[ATTRIBUTE1] [nvarchar](250) NULL,
	[ATTRIBUTE2] [nvarchar](250) NULL,
	[ATTRIBUTE3] [nvarchar](250) NULL,
	[ATTRIBUTE4] [nvarchar](250) NULL,
	[ATTRIBUTE5] [nvarchar](250) NULL,
	[ATTRIBUTE6] [nvarchar](250) NULL,
	[ATTRIBUTE7] [nvarchar](250) NULL,
	[ATTRIBUTE8] [nvarchar](250) NULL,
	[ATTRIBUTE9] [nvarchar](250) NULL,
	[ATTRIBUTE10] [nvarchar](250) NULL,
	[ATTRIBUTE11] [nvarchar](250) NULL,
	[ATTRIBUTE12] [nvarchar](250) NULL,
	[ATTRIBUTE13] [nvarchar](250) NULL,
	[ATTRIBUTE14] [nvarchar](250) NULL,
	[ATTRIBUTE15] [nvarchar](250) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [numeric](18, 0) NULL,
	[LAST_UPDATE_DATE] [datetime] NULL,
	[LAST_UPDATED_BY] [numeric](18, 0) NULL,
	[LAST_UPDATE_LOGIN] [numeric](18, 0) NULL
) ON [PRIMARY]
