package com.tbea.ic.operation.service.sbdczclwcqk.cpczwcqk;

public enum SBDCZCLWCQK_CZ_BYQ_Type{

	SBDCZCLWCQK_CZ_BYQ_CTXM_GN(2),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GN_EPCMS(3),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GN_BTMS(4),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GN_QTMS(5),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GJ(6),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GJ_EPCMS(7),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GJ_BTMS(8),
	SBDCZCLWCQK_CZ_BYQ_CTXM_GJ_QTMS(9),
	SBDCZCLWCQK_CZ_BYQ_WLMY(10),
	SBDCZCLWCQK_CZ_BYQ_FWL(11),
	SBDCZCLWCQK_CZ_BYQ_FWL_HYFSR(12),
	SBDCZCLWCQK_CZ_BYQ_FWL_WYFSR(13),
	SBDCZCLWCQK_CZ_BYQ_FWL_LWSR(14),
	SBDCZCLWCQK_CZ_BYQ_FWL_HMSR(15),
	SBDCZCLWCQK_CZ_BYQ_FWL_ZSSR(16),
	SBDCZCLWCQK_CZ_BYQ_FWL_JPDLSR(17),
	SBDCZCLWCQK_CZ_BYQ_FWL_RYBHSR(18),
	SBDCZCLWCQK_CZ_BYQ_FWL_DFSR(19),
	SBDCZCLWCQK_CZ_BYQ_FWLSQNSR(20),
	SBDCZCLWCQK_CZ_BYQ_FWLCYSR(21),
	SBDCZCLWCQK_CZ_BYQ_FWLQTSR(22),
	SBDCZCLWCQK_CZ_BYQ_TSCP(74),
	SBDCZCLWCQK_CZ_BYQ_FJHJB(72),
	SBDCZCLWCQK_CZ_BYQ_JTX(73);
    
	
    private int _value;

    private SBDCZCLWCQK_CZ_BYQ_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}