package com.tbea.ic.operation.service.sbdczclwcqk.cpczwcqk;

public enum SBDCZCLWCQK_CZ_XL_Type{

	SBDCZCLWCQK_CZ_XL_CTXM_GN(2),
	SBDCZCLWCQK_CZ_XL_CTXM_GN_EPCMS(3),
	SBDCZCLWCQK_CZ_XL_CTXM_GN_BTMS(4),
	SBDCZCLWCQK_CZ_XL_CTXM_GN_QTMS(5),
	SBDCZCLWCQK_CZ_XL_CTXM_GJ(6),
	SBDCZCLWCQK_CZ_XL_CTXM_GJ_EPCMS(7),
	SBDCZCLWCQK_CZ_XL_CTXM_GJ_BTMS(8),
	SBDCZCLWCQK_CZ_XL_CTXM_GJ_QTMS(9),
	SBDCZCLWCQK_CZ_XL_WLMY(10),
	SBDCZCLWCQK_CZ_XL_FWL(11),
	SBDCZCLWCQK_CZ_XL_FWL_HYFSR(12),
	SBDCZCLWCQK_CZ_XL_FWL_WYFSR(13),
	SBDCZCLWCQK_CZ_XL_FWL_LWSR(14),
	SBDCZCLWCQK_CZ_XL_FWL_HMSR(15),
	SBDCZCLWCQK_CZ_XL_FWL_ZSSR(16),
	SBDCZCLWCQK_CZ_XL_FWL_JPDLSR(17),
	SBDCZCLWCQK_CZ_XL_FWL_RYBHSR(18),
	SBDCZCLWCQK_CZ_XL_FWL_DFSR(19),
	SBDCZCLWCQK_CZ_XL_FWLSQNSR(20),
	SBDCZCLWCQK_CZ_XL_FWLCYSR(21),
	SBDCZCLWCQK_CZ_XL_FWLQTSR(22),
	SBDCZCLWCQK_CZ_XL_QT(1);
	
	
    private int _value;

    private SBDCZCLWCQK_CZ_XL_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}