package com.tbea.ic.operation.service.sbdczclwcqk.cpczwcqk;

public enum SBDCZCLWCQK_CZ_XL_Type{

	SBDCZCLWCQK_CZ_XL_CPFL_DX(59),
	SBDCZCLWCQK_CZ_XL_CPFL_BDX(60),
	SBDCZCLWCQK_CZ_XL_CPFL_JKX(61),
	SBDCZCLWCQK_CZ_XL_CPFL_KZDL(62),
	SBDCZCLWCQK_CZ_XL_CPFL_JLDL(63),
	SBDCZCLWCQK_CZ_XL_CPFL_DLDL(64),
	SBDCZCLWCQK_CZ_XL_CPFL_DCX(65),
	SBDCZCLWCQK_CZ_XL_CPFL_TZDL(66),
	SBDCZCLWCQK_CZ_XL_CPFL_DLFJ(67),
	SBDCZCLWCQK_CZ_XL_CPFL_TG(68),
	SBDCZCLWCQK_CZ_XL_CPFL_LG(69),
	SBDCZCLWCQK_CZ_XL_CPFL_PVC(70),
	SBDCZCLWCQK_CZ_XL_CPFL_GZL(71),
	SBDCZCLWCQK_CZ_XL_ZH_QT(1);
	
    private int _value;

    private SBDCZCLWCQK_CZ_XL_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}