package com.tbea.ic.operation.common.excel;

public enum SbdczclwcqkSheetType {
    SBDCZCLWCQK_CZ_BYQ_1,
    SBDCZCLWCQK_CZ_BYQ_2,
    SBDCZCLWCQK_CZ_BYQ_3,
    SBDCZCLWCQK_CZ_BYQ_4,
    SBDCZCLWCQK_CZ_BYQ_5,
    SBDCZCLWCQK_CZ_BYQ_6,
    SBDCZCLWCQK_CZ_BYQ_7,
    SBDCZCLWCQK_CZ_BYQ_8,
    SBDCZCLWCQK_CZ_BYQ_9,
    SBDCZCLWCQK_CZ_BYQ_10,
    SBDCZCLWCQK_CZ_BYQ_11,
    SBDCZCLWCQK_CZ_BYQ_12,
    END;
}
