package com.tbea.ic.operation.common.excel;

public enum YlfxwlyddmlspcsSheetType{
    YLFX_WLYMLSP_BYQ_ZH_1,
    YLFX_WLYMLSP_BYQ_ZH_2,
    YLFX_WLYMLSP_BYQ_ZH_3,
    YLFX_WLYMLSP_BYQ_ZH_4,
    YLFX_WLYMLSP_BYQ_ZH_5,
    YLFX_WLYMLSP_BYQ_ZH_6,
    YLFX_WLYMLSP_BYQ_ZH_7,
    YLFX_WLYMLSP_BYQ_ZH_8,
    YLFX_WLYMLSP_BYQ_ZH_9,
    YLFX_WLYMLSP_BYQ_ZH_10,
    YLFX_WLYMLSP_BYQ_ZH_11,
    YLFX_WLYMLSP_BYQ_ZH_12,
    END;
}