package com.tbea.ic.operation.service.sbdscqyqk.xfcpqy;

public enum SBDCPQY_XFCP_BYQ{

	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ(23),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_35KV_YX(24),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_66_110KV(25),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_220KV(26),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_330KV(27),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_500KV(28),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_750KV(29),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_JLBYQ_1000KV(30),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ(31),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ_400KV_YX(32),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ_500KV(33),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ_600KV(34),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ_800KV(35),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_ZLBYQ_PBDKQ(36),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_DKQ(37),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_DKQ_330KV_YX(38),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_DKQ_500KV(39),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_DKQ_750KV(40),
	SBDCZCLWCQK_CZ_BYQ_DYDJ_DKQ_1000KV(41),
	SBDCZCLWCQK_CZ_BYQ_CPFL_GSBYQ(42),
	SBDCZCLWCQK_CZ_BYQ_CPFL_GSBYQ_F(43),
	SBDCZCLWCQK_CZ_BYQ_CPFL_GSBYQ_H(44),
	SBDCZCLWCQK_CZ_BYQ_CPFL_GSBYQ_XSBDZ(45),
	SBDCZCLWCQK_CZ_BYQ_CPFL_GSBYQ_GSDKQ(46),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ(47),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ_GBB(48),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ_ZLB(49),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ_QYB(50),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ_YTB(51),
	SBDCZCLWCQK_CZ_BYQ_CPFL_TZBYQ_QT(52),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSL(53),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSL_PDZDH(54),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSL_KG(55),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSL_TG(56),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSL_HGQ(57),
	SBDCZCLWCQK_CZ_BYQ_CPFL_YSLWXPJ(58),
	SBDCZCLWCQK_CZ_BYQ_CPFL_T1(74),
	SBDCZCLWCQK_CZ_BYQ_CPFL_T1_FJHJB(72),
	SBDCZCLWCQK_CZ_BYQ_CPFL_T1_JTX(73);
    
    private int _value;

    private SBDCPQY_XFCP_BYQ(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}