package com.tbea.ic.operation.service.wgcpqk.wgcpylnlspcs;

public enum WGCPYLNL_BYQ_CPFL_Type{

	WGCPYLNL_BYQ_CPFL_GSBYQ(42),
	WGCPYLNL_BYQ_CPFL_GSBYQ_F(43),
	WGCPYLNL_BYQ_CPFL_GSBYQ_H(44),
	WGCPYLNL_BYQ_CPFL_GSBYQ_XSBDZ(45),
	WGCPYLNL_BYQ_CPFL_GSBYQ_GSDKQ(46),
	WGCPYLNL_BYQ_CPFL_TZBYQ(47),
	WGCPYLNL_BYQ_CPFL_TZBYQ_GBB(48),
	WGCPYLNL_BYQ_CPFL_TZBYQ_ZLB(49),
	WGCPYLNL_BYQ_CPFL_TZBYQ_QYB(50),
	WGCPYLNL_BYQ_CPFL_TZBYQ_YTB(51),
	WGCPYLNL_BYQ_CPFL_TZBYQ_QT(52),
	WGCPYLNL_BYQ_CPFL_YSL(53),
	WGCPYLNL_BYQ_CPFL_YSL_PDZDH(54),
	WGCPYLNL_BYQ_CPFL_YSL_KG(55),
	WGCPYLNL_BYQ_CPFL_YSL_TG(56),
	WGCPYLNL_BYQ_CPFL_YSL_HGQ(57),
	WGCPYLNL_BYQ_CPFL_YSLWXPJ(58);
	
	
    private int _value;

    private WGCPYLNL_BYQ_CPFL_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}