package com.tbea.ic.operation.service.wgcpqk.wgcpylnlspcs;

public enum WGCPYLNL_BYQ_DYDJ_Type{

	WGCPYLNL_BYQ_DYDJ_JLBYQ(23),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_35KV_YX(24),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_66_110KV(25),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_220KV(26),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_330KV(27),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_500KV(28),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_750KV(29),
	WGCPYLNL_BYQ_DYDJ_JLBYQ_1000KV(30),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ(31),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ_400KV_YX(32),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ_500KV(33),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ_600KV(34),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ_800KV(35),
	WGCPYLNL_BYQ_DYDJ_ZLBYQ_PBDKQ(36),
	WGCPYLNL_BYQ_DYDJ_DKQ(37),
	WGCPYLNL_BYQ_DYDJ_DKQ_330KV_YX(38),
	WGCPYLNL_BYQ_DYDJ_DKQ_500KV(39),
	WGCPYLNL_BYQ_DYDJ_DKQ_750KV(40),
	WGCPYLNL_BYQ_DYDJ_DKQ_1000KV(41);
	   
    private int _value;

    private WGCPYLNL_BYQ_DYDJ_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}