package com.tbea.ic.operation.service.wgcpqk.wgcpylnlspcs;

public enum WGCPYLNL_XL_ZH_Type{

	WGCPYLNL_XL_ZH_CTXM_GN(2),
	WGCPYLNL_XL_ZH_CTXM_GN_EPCMS(3),
	WGCPYLNL_XL_ZH_CTXM_GN_BTMS(4),
	WGCPYLNL_XL_ZH_CTXM_GN_QTMS(5),
	WGCPYLNL_XL_ZH_CTXM_GJ(6),
	WGCPYLNL_XL_ZH_CTXM_GJ_EPCMS(7),
	WGCPYLNL_XL_ZH_CTXM_GJ_BTMS(8),
	WGCPYLNL_XL_ZH_CTXM_GJ_QTMS(9),
	WGCPYLNL_XL_ZH_WLMY(10),
	WGCPYLNL_XL_ZH_FWL(11),
	WGCPYLNL_XL_ZH_FWL_HYFSR(12),
	WGCPYLNL_XL_ZH_FWL_WYFSR(13),
	WGCPYLNL_XL_ZH_FWL_LWSR(14),
	WGCPYLNL_XL_ZH_FWL_HMSR(15),
	WGCPYLNL_XL_ZH_FWL_ZSSR(16),
	WGCPYLNL_XL_ZH_FWL_JPDLSR(17),
	WGCPYLNL_XL_ZH_FWL_RYBHSR(18),
	WGCPYLNL_XL_ZH_FWL_DFSR(19),
	WGCPYLNL_XL_ZH_FWLSQNSR(20),
	WGCPYLNL_XL_ZH_FWLCYSR(21),
	WGCPYLNL_XL_ZH_FWLQTSR(22);
    
    private int _value;

    private WGCPYLNL_XL_ZH_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}