package com.tbea.ic.operation.service.sbdczclwcqk.cpclwcqk;

public enum SBDCZCLWCQK_CL_BYQ_Type{

	MLSPCS_BYQ_DYDJ_JLBYQ(23),
	MLSPCS_BYQ_DYDJ_JLBYQ_35KV_YX(24),
	MLSPCS_BYQ_DYDJ_JLBYQ_66_110KV(25),
	MLSPCS_BYQ_DYDJ_JLBYQ_220KV(26),
	MLSPCS_BYQ_DYDJ_JLBYQ_330KV(27),
	MLSPCS_BYQ_DYDJ_JLBYQ_500KV(28),
	MLSPCS_BYQ_DYDJ_JLBYQ_750KV(29),
	MLSPCS_BYQ_DYDJ_JLBYQ_1000KV(30),
	MLSPCS_BYQ_DYDJ_ZLBYQ(31),
	MLSPCS_BYQ_DYDJ_ZLBYQ_400KV_YX(32),
	MLSPCS_BYQ_DYDJ_ZLBYQ_500KV(33),
	MLSPCS_BYQ_DYDJ_ZLBYQ_600KV(34),
	MLSPCS_BYQ_DYDJ_ZLBYQ_800KV(35),
	MLSPCS_BYQ_DYDJ_ZLBYQ_PBDKQ(36),
	MLSPCS_BYQ_DYDJ_DKQ(37),
	MLSPCS_BYQ_DYDJ_DKQ_330KV_YX(38),
	MLSPCS_BYQ_DYDJ_DKQ_500KV(39),
	MLSPCS_BYQ_DYDJ_DKQ_750KV(40),
	MLSPCS_BYQ_DYDJ_DKQ_1000KV(41),
	MLSPCS_BYQ_CPFL_GSBYQ(42),
	MLSPCS_BYQ_CPFL_GSBYQ_F(43),
	MLSPCS_BYQ_CPFL_GSBYQ_H(44),
	//MLSPCS_BYQ_CPFL_GSBYQ_XSBDZ(45),
	MLSPCS_BYQ_CPFL_GSBYQ_GSDKQ(46),
	MLSPCS_BYQ_CPFL_77(77),
	MLSPCS_BYQ_CPFL_78(78),
	MLSPCS_BYQ_CPFL_79(79),
	MLSPCS_BYQ_CPFL_80(80),
	MLSPCS_BYQ_CPFL_QT_86(86),
	MLSPCS_BYQ_CPFL_81(81),
	MLSPCS_BYQ_CPFL_82(82),
	MLSPCS_BYQ_CPFL_83(83),
	MLSPCS_BYQ_CPFL_84(84),
	MLSPCS_BYQ_CPFL_QT_87(87),
	MLSPCS_BYQ_CPFL_TZBYQ(47),
	MLSPCS_BYQ_CPFL_TZBYQ_ZLB(49),
	MLSPCS_BYQ_CPFL_TZBYQ_QYB(50),
	MLSPCS_BYQ_CPFL_TZBYQ_GBB(48),
	MLSPCS_BYQ_CPFL_TZBYQ_YTB(51),
	MLSPCS_BYQ_CPFL_TZBYQ_QT(52),
	MLSPCS_BYQ_CPFL_YSL(53),
	MLSPCS_BYQ_CPFL_YSL_PDZDH(54),
	MLSPCS_BYQ_CPFL_YSL_KG(55),
	MLSPCS_BYQ_CPFL_YSL_TG(56),
	MLSPCS_BYQ_CPFL_YSL_HGQ(57),
	MLSPCS_BYQ_CPFL_YSLWXPJ(58),
	MLSPCS_BYQ_CPFL_YSLWXPJ_QT(85);
    
	
    private int _value;

    private SBDCZCLWCQK_CL_BYQ_Type(int value)
    {
        _value = value;
    }

    public int value()
    {
        return _value;
    }
}